services:

# Serviço de desenvolvimento
    dev:
        restart: always
        build:
            context: ./docker/dev
            dockerfile: dockerfile
        volumes:
            - ./docker/dev/scripts:/start
            - ./src:/src
            - ./:/fullbase
            - nvim-data:/home/node/.local
        ports:
            - "8042:8042"
        env_file:
            - .env

volumes:
  nvim-data:
