services:

# Serviço de desenvolvimento
    dev:
        restart: always
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile
        volumes:
            # - ./docker/dev/scripts:/start
            - ./src:/src
            - ./:/fullbase:cached
            - nvim-data:/home/node/.local
        ports:
            - "8043:8043"
        env_file:
            - .env

    api-gateway:
        depends_on:
          certificate-authority:
            condition: service_completed_successfully
        restart: always
        build:
          context: .
          dockerfile: containers/api-gateway/Dockerfile
        ports:
            - "8044:8044"
        volumes:
          - type: volume
            source: certs
            target: /certs
            volume:
              subpath: api-gateway

    auth:
        depends_on:
          certificate-authority:
            condition: service_completed_successfully
        restart: always
        build:
          context: .
          dockerfile: containers/auth/Dockerfile
        volumes:
          #only has access to relevant certificate
          - type: volume
            source: certs
            target: /certs
            volume:
              subpath: auth
          #another volume
          - auth-data:/data

    client:
        depends_on:
          certificate-authority:
            condition: service_completed_successfully
        restart: always
        build:
          context: .
          dockerfile: containers/client/Dockerfile
        volumes:
          #only has access to relevant certificate
          - type: volume
            source: certs
            target: /certs
            volume:
              subpath: client
        links:
          - "api-gateway:api.transcendence"
        ports:
            - "8042:8042"

    certificate-authority:
        build:
            context: containers/certificate-authority
        volumes:
          - certs:/out

volumes:
  nvim-data:
  auth-data:
  certs:
