services:

# Serviço de desenvolvimento
    dev:
        restart: always
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile
        volumes:
            # - ./docker/dev/scripts:/start
            - ./src:/src
            - ./:/fullbase:cached
            - nvim-data:/home/node/.local
        ports:
            - "8043:8043"
        env_file:
            - .env

    api-gateway:
        restart: always
        build:
          context: .
          dockerfile: containers/api-gateway/Dockerfile
        ports:
            - "8044:8044"
        volumes:
            - ./certs/api-gateway:/certs

    auth:
        restart: always
        build:
          context: .
          dockerfile: containers/auth/Dockerfile
        volumes:
          - ./certs/auth:/certs
          - auth-data:/data
        env_file:
            - .env

    client:
        restart: always
        build:
          context: .
          dockerfile: containers/client/Dockerfile
        volumes:
            - ./certs/client:/certs
        ports:
            - "8042:8042"

volumes:
  nvim-data:
  auth-data:
