services:

# Serviço de desenvolvimento
    dev:
        restart: always
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile
        volumes:
            # - ./docker/dev/scripts:/start
            - ./src:/src
            - ./:/fullbase:cached
            - nvim-data:/home/node/.local
        ports:
            - "8043:8043"
        env_file:
            - .env

    api-gateway:
        restart: always
        build:
          context: .
          dockerfile: containers/api-gateway/Dockerfile

    client:
        restart: always
        build:
          context: .
          dockerfile: containers/client/Dockerfile
        links:
          - "api-gateway:api.transcendence"
        ports:
            - "8042:8042"

volumes:
  nvim-data:
