services:

# Serviço de desenvolvimento
    dev:
        restart: always
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile
        volumes:
            # - ./docker/dev/scripts:/start
            - ./src:/src
            - ./:/fullbase:cached
            - nvim-data:/home/node/.local
        ports:
            - "8043:8043"
        env_file:
            - .env

    api-gateway:
        restart: always
        build:
          context: .
          dockerfile: containers/api-gateway/Dockerfile
        ports:
            - "8044:8044"

    auth:
        restart: always
        build:
          context: .
          dockerfile: containers/auth/Dockerfile
        volumes:
          - auth-data:/data

    client:
        restart: always
        build:
          context: .
          dockerfile: containers/client/Dockerfile
        links:
          - "api-gateway:api.transcendence"
        ports:
            - "8042:8042"

    elasticsearch:
        restart: always
        build:
            context: ./containers/elk-logs/elasticsearch
            dockerfile: Dockerfile
        container_name: elasticsearch
        volumes:
            - ./certs/elk:/usr/share/elasticsearch/config/certs
        environment:
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - discovery.type=single-node
            - ELASTIC_PASSWORD=secret
            - KIBANA_PASSWORD=secret
        mem_limit: 1g
        ports:
            - "9200:9200"
        depends_on:
            - certs-generator
        networks:
            - elk

    logstash:
        restart: always
        build:
            context: ./containers/elk-logs/logstash
            dockerfile: Dockerfile
        container_name: logstash
        volumes:
            - ./certs/elk:/usr/share/logstash/config/certs
        environment:
            - LS_JAVA_OPTS=-Xms256m -Xmx256m
            - ELASTIC_PASSWORD=secret
        mem_limit: 512m
        ports:
            - "5044:5044"
        depends_on:
            - elasticsearch
        networks:
            - elk

    kibana:
        restart: always
        build:
            context: ./containers/elk-logs/kibana
            dockerfile: Dockerfile
        container_name: kibana
        volumes:
            - ./certs/elk:/usr/share/kibana/config/certs
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - KIBANA_PASSWORD=secret
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        networks:
            - elk

    filebeat:
        restart: always
        build:
            context: ./containers/elk-logs/filebeat
            dockerfile: Dockerfile
        container_name: filebeat
        user: root
        volumes:
            - ./certs/elk:/usr/share/filebeat/config/certs
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
            - logstash
        networks:
            - elk

    certs-generator:
        build:
            context: ./containers/elk-logs/certs-generator
            dockerfile: Dockerfile
        container_name: temp-certs-generator
        volumes:
            - ./certs/elk:/certs

volumes:
  nvim-data:
  auth-data:

networks:
  elk:
    driver: bridge

secrets:
    elastic_password:
        file: ./secrets/elastic_password.txt