filebeat.inputs:
  - type: filestream
    enabled: true
    id: "transcendence"
    paths:
      - /var/lib/docker/containers/*/*.log
    parsers:
      - container:
          stream: all
          format: auto

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true

output.elasticsearch:
  enabled: false

output.logstash:
  hosts: ["logstash:5044"]
