@startuml
skinparam componentLayout vertical

package FrontEnd {
	component [Client]
}


package BackEnd {
	component [API Gateway\n(NodeJs app)] as AG

	component [Auth]
	database AuthDB

}

Client --down--> AG
AG --> Client
AG <--down--> Auth

Auth <--> AuthDB

@enduml
