@startuml
skinparam componentLayout vertical

package FrontEnd {
	component [Client]
}

component [API Gateway\n(NodeJs app)] as AG

package BackEnd {
	component [Users]
	database UsersDB

	component [Auth]

	component [Tournament]
	database TournamentDB
}

Client --down--> AG
AG --> Client
AG --down--> Users
Users --> AG

Users <--> UsersDB
Tournament <--> TournamentDB

@enduml
